#!/usr/bin/env bash

if [[ ! -f $(which buf) ]]; then
  printf "Could not find 'buf' executable. Ensure that it is installed in your path.\n" >&2
  exit 1
fi

gen_desc="Compiles protos in the protos directory using plugins found in buf.gen.yaml"
gen() {
  printf "Compiling protocol buffers...\n"
  rm -rf gen
  buf generate protos --include-imports

  targets=""

  for target in $(ls gen); do
    targets+="- $target\n"
  done

  printf "Successfully generated code for the following targets:\n$targets"
}

lint_desc="Lints protos found in the protos directory"
lint() {
  buf lint protos
}

read -r -d '' sift_usage << EOT
Script containing Sift protobuf utilities.

Usage: sift [options] [command]

Available commands:
  gen             $gen_desc
  lint            $lint_desc

Available options:
  -h, --help      Show help text.
EOT

if [[ "${#@}" == "0" ]]; then
  printf "$sift_usage\n"
  exit 0
fi

case "$1" in
  -h|--help) printf "$usage\n"
  ;;
  lint) lint
  ;;
  gen) gen
  ;;
  *)
    printf "Unrecognized argument '$1'. Please refer to '--help' for a list of valid arguments.\n" >&2
    exit 1
  ;;
esac

exit 0
