"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sift.common.type.v1.organization_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ApiKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREATED_DATE_FIELD_NUMBER: builtins.int
    CREATED_BY_USER_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    api_key_id: builtins.str
    name: builtins.str
    created_by_user_id: builtins.str
    user_id: builtins.str
    @property
    def created_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        api_key_id: builtins.str = ...,
        name: builtins.str = ...,
        created_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_by_user_id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_date", b"created_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["api_key_id", b"api_key_id", "created_by_user_id", b"created_by_user_id", "created_date", b"created_date", "name", b"name", "user_id", b"user_id"]) -> None: ...

global___ApiKey = ApiKey

@typing.final
class CreateApiKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEY_FIELD_NUMBER: builtins.int
    @property
    def api_key(self) -> global___CreatedApiKey: ...
    def __init__(
        self,
        *,
        api_key: global___CreatedApiKey | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["api_key", b"api_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["api_key", b"api_key"]) -> None: ...

global___CreateApiKeyResponse = CreateApiKeyResponse

@typing.final
class CreatedApiKey(google.protobuf.message.Message):
    """CreatedApiKey includes the key, which will only be returned on creation, so having a separate type makes the "never return the key a second time" semantics clear"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    CREATED_DATE_FIELD_NUMBER: builtins.int
    CREATED_BY_USER_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    api_key_id: builtins.str
    name: builtins.str
    key: builtins.str
    created_by_user_id: builtins.str
    user_id: builtins.str
    @property
    def created_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        api_key_id: builtins.str = ...,
        name: builtins.str = ...,
        key: builtins.str = ...,
        created_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        created_by_user_id: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_date", b"created_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["api_key_id", b"api_key_id", "created_by_user_id", b"created_by_user_id", "created_date", b"created_date", "key", b"key", "name", b"name", "user_id", b"user_id"]) -> None: ...

global___CreatedApiKey = CreatedApiKey

@typing.final
class ListApiKeysRequest(google.protobuf.message.Message):
    """The request for a call to ApiKeyService.ListApiKeys."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    page_size: builtins.int
    """The maximum number of api keys to return.
    The service may return fewer than this value.
    The maximum value is 1000; values above 1000 will be coerced to 1000.
    """
    page_token: builtins.str
    """A page token, received from a previous `ListApiKeys` call.
    Provide this to retrieve the subsequent page.
    When paginating, all other parameters provided to `ListApiKeys` must match
    the call that provided the page token.
    """
    filter: builtins.str
    """A [Common Expression Language (CEL)](https://github.com/google/cel-spec) filter string.
    Available fields to filter by are `api_key_id`, `user_id`, `created_by_user_id`, and `name`.
    For further information about how to use CELs, please refer to [this guide](https://github.com/google/cel-spec/blob/master/doc/langdef.md#standard-definitions).
    For more information about the fields used for filtering, please refer to [this definition](/docs/api/grpc/protocol-buffers/channels#channel). Optional.
    """
    order_by: builtins.str
    """How to order the retrieved channels. Formatted as a comma-separated string i.e. "FIELD_NAME[ desc],...".
    Available fields to order_by are `name` and `created_date`.
    If left empty, items are ordered by `created_date` in ascending order (oldest-first).
    For more information about the format of this field, read [this](https://google.aip.dev/132#ordering)
    Example: "name desc,created_date"
    """
    def __init__(
        self,
        *,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
        order_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "order_by", b"order_by", "page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListApiKeysRequest = ListApiKeysRequest

@typing.final
class ListApiKeysResponse(google.protobuf.message.Message):
    """The result of a call to ApiKeyService.ListApiKeys."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEYS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    @property
    def api_keys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApiKey]: ...
    def __init__(
        self,
        *,
        api_keys: collections.abc.Iterable[global___ApiKey] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["api_keys", b"api_keys", "next_page_token", b"next_page_token"]) -> None: ...

global___ListApiKeysResponse = ListApiKeysResponse

@typing.final
class CreateApiKeyRequest(google.protobuf.message.Message):
    """The request for a call to ApiKeyService.CreateApiKey."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name for the new ApiKey. Required."""
    user_id: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "user_id", b"user_id"]) -> None: ...

global___CreateApiKeyRequest = CreateApiKeyRequest

@typing.final
class DeleteApiKeyRequest(google.protobuf.message.Message):
    """The request for a call to ApiKeyService.DeleteApiKey."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEY_ID_FIELD_NUMBER: builtins.int
    api_key_id: builtins.str
    def __init__(
        self,
        *,
        api_key_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["api_key_id", b"api_key_id"]) -> None: ...

global___DeleteApiKeyRequest = DeleteApiKeyRequest

@typing.final
class DeleteApiKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteApiKeyResponse = DeleteApiKeyResponse

@typing.final
class ApiKeyOrganizationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ApiKeyOrganizationRequest = ApiKeyOrganizationRequest

@typing.final
class ApiKeyOrganizationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORGANIZATION_FIELD_NUMBER: builtins.int
    @property
    def organization(self) -> sift.common.type.v1.organization_pb2.Organization: ...
    def __init__(
        self,
        *,
        organization: sift.common.type.v1.organization_pb2.Organization | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["organization", b"organization"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["organization", b"organization"]) -> None: ...

global___ApiKeyOrganizationResponse = ApiKeyOrganizationResponse
