# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sift.resource_attribute.v1 import resource_attribute_pb2 as sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2


class ResourceAttributeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateResourceAttributeKey = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttributeKey',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyResponse.FromString,
                )
        self.GetResourceAttributeKey = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttributeKey',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyResponse.FromString,
                )
        self.ListResourceAttributeKeys = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributeKeys',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysResponse.FromString,
                )
        self.UpdateResourceAttributeKey = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/UpdateResourceAttributeKey',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyResponse.FromString,
                )
        self.ArchiveResourceAttributeKey = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttributeKey',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyResponse.FromString,
                )
        self.UnarchiveResourceAttributeKey = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttributeKey',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyResponse.FromString,
                )
        self.BatchArchiveResourceAttributeKeys = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributeKeys',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysResponse.FromString,
                )
        self.BatchUnarchiveResourceAttributeKeys = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributeKeys',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysResponse.FromString,
                )
        self.CreateResourceAttributeEnumValue = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttributeEnumValue',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueResponse.FromString,
                )
        self.GetResourceAttributeEnumValue = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttributeEnumValue',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueResponse.FromString,
                )
        self.ListResourceAttributeEnumValues = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributeEnumValues',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesResponse.FromString,
                )
        self.UpdateResourceAttributeEnumValue = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/UpdateResourceAttributeEnumValue',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueResponse.FromString,
                )
        self.ArchiveResourceAttributeEnumValue = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttributeEnumValue',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueResponse.FromString,
                )
        self.UnarchiveResourceAttributeEnumValue = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttributeEnumValue',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueResponse.FromString,
                )
        self.BatchArchiveResourceAttributeEnumValues = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributeEnumValues',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesResponse.FromString,
                )
        self.BatchUnarchiveResourceAttributeEnumValues = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributeEnumValues',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesResponse.FromString,
                )
        self.CreateResourceAttribute = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttribute',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeResponse.FromString,
                )
        self.BatchCreateResourceAttributes = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchCreateResourceAttributes',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesResponse.FromString,
                )
        self.GetResourceAttribute = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttribute',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeResponse.FromString,
                )
        self.ListResourceAttributes = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributes',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesResponse.FromString,
                )
        self.ListResourceAttributesByEntity = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributesByEntity',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityResponse.FromString,
                )
        self.ArchiveResourceAttribute = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttribute',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeResponse.FromString,
                )
        self.UnarchiveResourceAttribute = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttribute',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeResponse.FromString,
                )
        self.BatchArchiveResourceAttributes = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributes',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesResponse.FromString,
                )
        self.BatchUnarchiveResourceAttributes = channel.unary_unary(
                '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributes',
                request_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesRequest.SerializeToString,
                response_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesResponse.FromString,
                )


class ResourceAttributeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateResourceAttributeKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceAttributeKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceAttributeKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResourceAttributeKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveResourceAttributeKey(self, request, context):
        """Archives a resource_attribute key AND all its associated enum values AND all its associated resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnarchiveResourceAttributeKey(self, request, context):
        """Unarchives a resource_attribute key BUT NOT its associated enum values OR resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchArchiveResourceAttributeKeys(self, request, context):
        """Archives multiple resource_attribute keys AND all their associated enum values AND all their associated resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUnarchiveResourceAttributeKeys(self, request, context):
        """Unarchives multiple resource_attribute keys BUT NOT their associated enum values OR resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResourceAttributeEnumValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceAttributeEnumValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceAttributeEnumValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResourceAttributeEnumValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveResourceAttributeEnumValue(self, request, context):
        """Archives an enum value and migrates all resource-attributes with that value to a replacement value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnarchiveResourceAttributeEnumValue(self, request, context):
        """Unarchives an enum value BUT DOES NOT migrate resource-attributes with a replacement value back to the original value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchArchiveResourceAttributeEnumValues(self, request, context):
        """Archives multiple enum values and migrates all resource-attributes with those values to their respective replacement values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUnarchiveResourceAttributeEnumValues(self, request, context):
        """Unarchives multiple enum values BUT DOES NOT migrate resource-attributes with a replacement value back to the original value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResourceAttribute(self, request, context):
        """Creates relation between an Entity and a ResourceAttribute Key and Value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreateResourceAttributes(self, request, context):
        """Creates resource-attributes for multiple entities with the same key-value pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceAttributesByEntity(self, request, context):
        """Lists all resource-attributes for a specific entity. Excludes archived by default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveResourceAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnarchiveResourceAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchArchiveResourceAttributes(self, request, context):
        """Archives multiple resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUnarchiveResourceAttributes(self, request, context):
        """Unarchives multiple resource-attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceAttributeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateResourceAttributeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResourceAttributeKey,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyResponse.SerializeToString,
            ),
            'GetResourceAttributeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceAttributeKey,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyResponse.SerializeToString,
            ),
            'ListResourceAttributeKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceAttributeKeys,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysResponse.SerializeToString,
            ),
            'UpdateResourceAttributeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResourceAttributeKey,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyResponse.SerializeToString,
            ),
            'ArchiveResourceAttributeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveResourceAttributeKey,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyResponse.SerializeToString,
            ),
            'UnarchiveResourceAttributeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UnarchiveResourceAttributeKey,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyResponse.SerializeToString,
            ),
            'BatchArchiveResourceAttributeKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchArchiveResourceAttributeKeys,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysResponse.SerializeToString,
            ),
            'BatchUnarchiveResourceAttributeKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUnarchiveResourceAttributeKeys,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysResponse.SerializeToString,
            ),
            'CreateResourceAttributeEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResourceAttributeEnumValue,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueResponse.SerializeToString,
            ),
            'GetResourceAttributeEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceAttributeEnumValue,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueResponse.SerializeToString,
            ),
            'ListResourceAttributeEnumValues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceAttributeEnumValues,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesResponse.SerializeToString,
            ),
            'UpdateResourceAttributeEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResourceAttributeEnumValue,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueResponse.SerializeToString,
            ),
            'ArchiveResourceAttributeEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveResourceAttributeEnumValue,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueResponse.SerializeToString,
            ),
            'UnarchiveResourceAttributeEnumValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UnarchiveResourceAttributeEnumValue,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueResponse.SerializeToString,
            ),
            'BatchArchiveResourceAttributeEnumValues': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchArchiveResourceAttributeEnumValues,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesResponse.SerializeToString,
            ),
            'BatchUnarchiveResourceAttributeEnumValues': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUnarchiveResourceAttributeEnumValues,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesResponse.SerializeToString,
            ),
            'CreateResourceAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResourceAttribute,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeResponse.SerializeToString,
            ),
            'BatchCreateResourceAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreateResourceAttributes,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesResponse.SerializeToString,
            ),
            'GetResourceAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceAttribute,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeResponse.SerializeToString,
            ),
            'ListResourceAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceAttributes,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesResponse.SerializeToString,
            ),
            'ListResourceAttributesByEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceAttributesByEntity,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityResponse.SerializeToString,
            ),
            'ArchiveResourceAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveResourceAttribute,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeResponse.SerializeToString,
            ),
            'UnarchiveResourceAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.UnarchiveResourceAttribute,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeResponse.SerializeToString,
            ),
            'BatchArchiveResourceAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchArchiveResourceAttributes,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesResponse.SerializeToString,
            ),
            'BatchUnarchiveResourceAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUnarchiveResourceAttributes,
                    request_deserializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesRequest.FromString,
                    response_serializer=sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sift.resource_attribute.v1.ResourceAttributeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResourceAttributeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateResourceAttributeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttributeKey',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceAttributeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttributeKey',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResourceAttributeKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributeKeys',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateResourceAttributeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/UpdateResourceAttributeKey',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ArchiveResourceAttributeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttributeKey',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnarchiveResourceAttributeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttributeKey',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchArchiveResourceAttributeKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributeKeys',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUnarchiveResourceAttributeKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributeKeys',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateResourceAttributeEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttributeEnumValue',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceAttributeEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttributeEnumValue',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResourceAttributeEnumValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributeEnumValues',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributeEnumValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateResourceAttributeEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/UpdateResourceAttributeEnumValue',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UpdateResourceAttributeEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ArchiveResourceAttributeEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttributeEnumValue',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnarchiveResourceAttributeEnumValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttributeEnumValue',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeEnumValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchArchiveResourceAttributeEnumValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributeEnumValues',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributeEnumValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUnarchiveResourceAttributeEnumValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributeEnumValues',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributeEnumValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateResourceAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/CreateResourceAttribute',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.CreateResourceAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchCreateResourceAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchCreateResourceAttributes',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchCreateResourceAttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/GetResourceAttribute',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.GetResourceAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResourceAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributes',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListResourceAttributesByEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ListResourceAttributesByEntity',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ListResourceAttributesByEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ArchiveResourceAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/ArchiveResourceAttribute',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.ArchiveResourceAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnarchiveResourceAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/UnarchiveResourceAttribute',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.UnarchiveResourceAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchArchiveResourceAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchArchiveResourceAttributes',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchArchiveResourceAttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUnarchiveResourceAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sift.resource_attribute.v1.ResourceAttributeService/BatchUnarchiveResourceAttributes',
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesRequest.SerializeToString,
            sift_dot_resource__attribute_dot_v1_dot_resource__attribute__pb2.BatchUnarchiveResourceAttributesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
