---
asset_name: LunarVehicle0
flows:
  - name: readings
    channels:
      - name: velocity
        data_type: CHANNEL_DATA_TYPE_DOUBLE
        description: speed
        unit: Miles Per Hour
        component: mainmotor
      - name: voltage
        data_type: CHANNEL_DATA_TYPE_INT_32
        description: voltage at the source
        unit: Volts
