# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sift/common/type/v1/resource_identifier.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-sift/common/type/v1/resource_identifier.proto\x12\x13sift.common.type.v1\x1a\x1fgoogle/api/field_behavior.proto\"U\n\x12ResourceIdentifier\x12\x10\n\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1f\n\nclient_key\x18\x02 \x01(\tH\x00R\tclientKeyB\x0c\n\nidentifier\"C\n\rNamedResource\x12\x10\n\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n\x04name\x18\x02 \x01(\tH\x00R\x04nameB\n\n\x08resource\"\x96\x01\n\x13ResourceIdentifiers\x12,\n\x03ids\x18\x01 \x01(\x0b\x32\x18.sift.common.type.v1.IdsH\x00R\x03ids\x12\x42\n\x0b\x63lient_keys\x18\x02 \x01(\x0b\x32\x1f.sift.common.type.v1.ClientKeysH\x00R\nclientKeysB\r\n\x0bidentifiers\"\x7f\n\x0eNamedResources\x12,\n\x03ids\x18\x01 \x01(\x0b\x32\x18.sift.common.type.v1.IdsH\x00R\x03ids\x12\x32\n\x05names\x18\x02 \x01(\x0b\x32\x1a.sift.common.type.v1.NamesH\x00R\x05namesB\x0b\n\tresources\"\x1c\n\x03Ids\x12\x15\n\x03ids\x18\x01 \x03(\tB\x03\xe0\x41\x02R\x03ids\"2\n\nClientKeys\x12$\n\x0b\x63lient_keys\x18\x01 \x03(\tB\x03\xe0\x41\x02R\nclientKeys\"\"\n\x05Names\x12\x19\n\x05names\x18\x01 \x03(\tB\x03\xe0\x41\x02R\x05namesB\xa1\x01\n\x17\x63om.sift.common.type.v1B\x17ResourceIdentifierProtoP\x01\xa2\x02\x03SCT\xaa\x02\x13Sift.Common.Type.V1\xca\x02\x13Sift\\Common\\Type\\V1\xe2\x02\x1fSift\\Common\\Type\\V1\\GPBMetadata\xea\x02\x16Sift::Common::Type::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sift.common.type.v1.resource_identifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.sift.common.type.v1B\027ResourceIdentifierProtoP\001\242\002\003SCT\252\002\023Sift.Common.Type.V1\312\002\023Sift\\Common\\Type\\V1\342\002\037Sift\\Common\\Type\\V1\\GPBMetadata\352\002\026Sift::Common::Type::V1'
  _globals['_IDS'].fields_by_name['ids']._loaded_options = None
  _globals['_IDS'].fields_by_name['ids']._serialized_options = b'\340A\002'
  _globals['_CLIENTKEYS'].fields_by_name['client_keys']._loaded_options = None
  _globals['_CLIENTKEYS'].fields_by_name['client_keys']._serialized_options = b'\340A\002'
  _globals['_NAMES'].fields_by_name['names']._loaded_options = None
  _globals['_NAMES'].fields_by_name['names']._serialized_options = b'\340A\002'
  _globals['_RESOURCEIDENTIFIER']._serialized_start=103
  _globals['_RESOURCEIDENTIFIER']._serialized_end=188
  _globals['_NAMEDRESOURCE']._serialized_start=190
  _globals['_NAMEDRESOURCE']._serialized_end=257
  _globals['_RESOURCEIDENTIFIERS']._serialized_start=260
  _globals['_RESOURCEIDENTIFIERS']._serialized_end=410
  _globals['_NAMEDRESOURCES']._serialized_start=412
  _globals['_NAMEDRESOURCES']._serialized_end=539
  _globals['_IDS']._serialized_start=541
  _globals['_IDS']._serialized_end=569
  _globals['_CLIENTKEYS']._serialized_start=571
  _globals['_CLIENTKEYS']._serialized_end=621
  _globals['_NAMES']._serialized_start=623
  _globals['_NAMES']._serialized_end=657
# @@protoc_insertion_point(module_scope)
