"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import sift.principal_attributes.v1.principal_attributes_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class PrincipalAttributeServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    CreatePrincipalAttributeKey: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyResponse,
    ]
    """Creates a principal attribute key."""

    GetPrincipalAttributeKey: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyResponse,
    ]
    """Retrieves a principal attribute key."""

    ListPrincipalAttributeKeys: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysResponse,
    ]
    """Lists principal attribute keys, respecting the provided filter."""

    UpdatePrincipalAttributeKey: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyResponse,
    ]
    """Updates an existing principal attribute key."""

    CheckPrincipalAttributeKeyArchiveImpact: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactResponse,
    ]

    ArchivePrincipalAttributeKeys: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysResponse,
    ]
    """Batch archives principal attribute keys AND all their associated principal attribute values."""

    UnarchivePrincipalAttributeKeys: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysResponse,
    ]
    """Batch unarchives principal attribute keys."""

    BatchCreatePrincipalAttributeValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueResponse,
    ]
    """Creates a principal attribute value for multiple principals in a single operation."""

    GetPrincipalAttributeValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueResponse,
    ]
    """Retrieves a principal attribute value."""

    ListPrincipalAttributeKeyValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesResponse,
    ]
    """Lists principal attribute values for a given principal attribute key, respecting the provided filter."""

    ListPrincipalAttributeValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesResponse,
    ]
    """Lists principal attribute values, respecting the provided filter."""

    ArchivePrincipalAttributeValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesResponse,
    ]
    """Batch archives principal attribute values."""

    UnarchivePrincipalAttributeValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesResponse,
    ]
    """Batch unarchives principal attribute values."""

    CreatePrincipalAttributeEnumValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueResponse,
    ]
    """Creates a principal attribute enum value."""

    GetPrincipalAttributeEnumValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueResponse,
    ]
    """Retrieves a principal attribute enum value."""

    ListPrincipalAttributeEnumValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesResponse,
    ]
    """Lists principal attribute enum values for a given principal attribute key."""

    UpdatePrincipalAttributeEnumValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueResponse,
    ]
    """Updates an existing principal attribute enum value."""

    ArchivePrincipalAttributeEnumValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueResponse,
    ]
    """Archives a principal attribute enum value and migrates all principal attribute values with that enum value to a replacement enum value."""

    UnarchivePrincipalAttributeEnumValue: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueResponse,
    ]
    """Unarchives a principal attribute enum value BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

    BatchArchivePrincipalAttributeEnumValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesResponse,
    ]
    """Archives multiple principal attribute enum values and migrates all principal attribute values with those enum values to their respective replacement enum values."""

    BatchUnarchivePrincipalAttributeEnumValues: grpc.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesResponse,
    ]
    """Unarchives multiple principal attribute enum values BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

class PrincipalAttributeServiceAsyncStub:
    CreatePrincipalAttributeKey: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyResponse,
    ]
    """Creates a principal attribute key."""

    GetPrincipalAttributeKey: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyResponse,
    ]
    """Retrieves a principal attribute key."""

    ListPrincipalAttributeKeys: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysResponse,
    ]
    """Lists principal attribute keys, respecting the provided filter."""

    UpdatePrincipalAttributeKey: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyResponse,
    ]
    """Updates an existing principal attribute key."""

    CheckPrincipalAttributeKeyArchiveImpact: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactResponse,
    ]

    ArchivePrincipalAttributeKeys: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysResponse,
    ]
    """Batch archives principal attribute keys AND all their associated principal attribute values."""

    UnarchivePrincipalAttributeKeys: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysResponse,
    ]
    """Batch unarchives principal attribute keys."""

    BatchCreatePrincipalAttributeValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueResponse,
    ]
    """Creates a principal attribute value for multiple principals in a single operation."""

    GetPrincipalAttributeValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueResponse,
    ]
    """Retrieves a principal attribute value."""

    ListPrincipalAttributeKeyValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesResponse,
    ]
    """Lists principal attribute values for a given principal attribute key, respecting the provided filter."""

    ListPrincipalAttributeValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesResponse,
    ]
    """Lists principal attribute values, respecting the provided filter."""

    ArchivePrincipalAttributeValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesResponse,
    ]
    """Batch archives principal attribute values."""

    UnarchivePrincipalAttributeValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesResponse,
    ]
    """Batch unarchives principal attribute values."""

    CreatePrincipalAttributeEnumValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueResponse,
    ]
    """Creates a principal attribute enum value."""

    GetPrincipalAttributeEnumValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueResponse,
    ]
    """Retrieves a principal attribute enum value."""

    ListPrincipalAttributeEnumValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesResponse,
    ]
    """Lists principal attribute enum values for a given principal attribute key."""

    UpdatePrincipalAttributeEnumValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueResponse,
    ]
    """Updates an existing principal attribute enum value."""

    ArchivePrincipalAttributeEnumValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueResponse,
    ]
    """Archives a principal attribute enum value and migrates all principal attribute values with that enum value to a replacement enum value."""

    UnarchivePrincipalAttributeEnumValue: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueResponse,
    ]
    """Unarchives a principal attribute enum value BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

    BatchArchivePrincipalAttributeEnumValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesResponse,
    ]
    """Archives multiple principal attribute enum values and migrates all principal attribute values with those enum values to their respective replacement enum values."""

    BatchUnarchivePrincipalAttributeEnumValues: grpc.aio.UnaryUnaryMultiCallable[
        sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesRequest,
        sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesResponse,
    ]
    """Unarchives multiple principal attribute enum values BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

class PrincipalAttributeServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def CreatePrincipalAttributeKey(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeKeyResponse]]:
        """Creates a principal attribute key."""

    @abc.abstractmethod
    def GetPrincipalAttributeKey(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeKeyResponse]]:
        """Retrieves a principal attribute key."""

    @abc.abstractmethod
    def ListPrincipalAttributeKeys(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeysResponse]]:
        """Lists principal attribute keys, respecting the provided filter."""

    @abc.abstractmethod
    def UpdatePrincipalAttributeKey(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeKeyResponse]]:
        """Updates an existing principal attribute key."""

    @abc.abstractmethod
    def CheckPrincipalAttributeKeyArchiveImpact(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.CheckPrincipalAttributeKeyArchiveImpactResponse]]: ...

    @abc.abstractmethod
    def ArchivePrincipalAttributeKeys(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeKeysResponse]]:
        """Batch archives principal attribute keys AND all their associated principal attribute values."""

    @abc.abstractmethod
    def UnarchivePrincipalAttributeKeys(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeKeysResponse]]:
        """Batch unarchives principal attribute keys."""

    @abc.abstractmethod
    def BatchCreatePrincipalAttributeValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.BatchCreatePrincipalAttributeValueResponse]]:
        """Creates a principal attribute value for multiple principals in a single operation."""

    @abc.abstractmethod
    def GetPrincipalAttributeValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeValueResponse]]:
        """Retrieves a principal attribute value."""

    @abc.abstractmethod
    def ListPrincipalAttributeKeyValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeKeyValuesResponse]]:
        """Lists principal attribute values for a given principal attribute key, respecting the provided filter."""

    @abc.abstractmethod
    def ListPrincipalAttributeValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeValuesResponse]]:
        """Lists principal attribute values, respecting the provided filter."""

    @abc.abstractmethod
    def ArchivePrincipalAttributeValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeValuesResponse]]:
        """Batch archives principal attribute values."""

    @abc.abstractmethod
    def UnarchivePrincipalAttributeValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeValuesResponse]]:
        """Batch unarchives principal attribute values."""

    @abc.abstractmethod
    def CreatePrincipalAttributeEnumValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.CreatePrincipalAttributeEnumValueResponse]]:
        """Creates a principal attribute enum value."""

    @abc.abstractmethod
    def GetPrincipalAttributeEnumValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.GetPrincipalAttributeEnumValueResponse]]:
        """Retrieves a principal attribute enum value."""

    @abc.abstractmethod
    def ListPrincipalAttributeEnumValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ListPrincipalAttributeEnumValuesResponse]]:
        """Lists principal attribute enum values for a given principal attribute key."""

    @abc.abstractmethod
    def UpdatePrincipalAttributeEnumValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.UpdatePrincipalAttributeEnumValueResponse]]:
        """Updates an existing principal attribute enum value."""

    @abc.abstractmethod
    def ArchivePrincipalAttributeEnumValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.ArchivePrincipalAttributeEnumValueResponse]]:
        """Archives a principal attribute enum value and migrates all principal attribute values with that enum value to a replacement enum value."""

    @abc.abstractmethod
    def UnarchivePrincipalAttributeEnumValue(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.UnarchivePrincipalAttributeEnumValueResponse]]:
        """Unarchives a principal attribute enum value BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

    @abc.abstractmethod
    def BatchArchivePrincipalAttributeEnumValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.BatchArchivePrincipalAttributeEnumValuesResponse]]:
        """Archives multiple principal attribute enum values and migrates all principal attribute values with those enum values to their respective replacement enum values."""

    @abc.abstractmethod
    def BatchUnarchivePrincipalAttributeEnumValues(
        self,
        request: sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesRequest,
        context: _ServicerContext,
    ) -> typing.Union[sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesResponse, collections.abc.Awaitable[sift.principal_attributes.v1.principal_attributes_pb2.BatchUnarchivePrincipalAttributeEnumValuesResponse]]:
        """Unarchives multiple principal attribute enum values BUT DOES NOT migrate principal attribute values with a replacement value back to the original value."""

def add_PrincipalAttributeServiceServicer_to_server(servicer: PrincipalAttributeServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
