"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sift.common.v1.filter_field_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetFilterGrammarRequest(google.protobuf.message.Message):
    """The request for a call to `FilterGrammarService_GetFilterGrammar`."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetFilterGrammarRequest = GetFilterGrammarRequest

@typing.final
class GetFilterGrammarResponse(google.protobuf.message.Message):
    """The response of a call to `FilterGrammarService_GetFilterGrammar`."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPES_FIELD_NUMBER: builtins.int
    GLOBAL_FUNCTIONS_FIELD_NUMBER: builtins.int
    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilterTypeGrammar]:
        """Operators and member functions available for each built-in field type."""

    @property
    def global_functions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilterFunction]:
        """Functions usable anywhere in an expression rather than bound to a field,
        e.g. now(), duration(...), timestamp(...).
        """

    def __init__(
        self,
        *,
        types: collections.abc.Iterable[global___FilterTypeGrammar] | None = ...,
        global_functions: collections.abc.Iterable[global___FilterFunction] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["global_functions", b"global_functions", "types", b"types"]) -> None: ...

global___GetFilterGrammarResponse = GetFilterGrammarResponse

@typing.final
class FilterTypeGrammar(google.protobuf.message.Message):
    """FilterTypeGrammar lists the operators and member functions valid for one
    built-in field type.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    OPERATORS_FIELD_NUMBER: builtins.int
    FUNCTIONS_FIELD_NUMBER: builtins.int
    type: sift.common.v1.filter_field_pb2.FilterFieldType.ValueType
    @property
    def operators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilterOperator]: ...
    @property
    def functions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilterFunction]: ...
    def __init__(
        self,
        *,
        type: sift.common.v1.filter_field_pb2.FilterFieldType.ValueType = ...,
        operators: collections.abc.Iterable[global___FilterOperator] | None = ...,
        functions: collections.abc.Iterable[global___FilterFunction] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["functions", b"functions", "operators", b"operators", "type", b"type"]) -> None: ...

global___FilterTypeGrammar = FilterTypeGrammar

@typing.final
class FilterOperator(google.protobuf.message.Message):
    """A CEL infix operator, with display copy for a UI."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    token: builtins.str
    """The literal CEL token, e.g. "==", "!=", "<", "in"."""
    display_name: builtins.str
    """Short label for a UI control, e.g. "Equals", "In"."""
    description: builtins.str
    """Optional longer explanation of what the operator matches."""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        display_name: builtins.str = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "display_name", b"display_name", "token", b"token"]) -> None: ...

global___FilterOperator = FilterOperator

@typing.final
class FilterFunction(google.protobuf.message.Message):
    """A CEL function, with display copy for a UI."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The CEL function name, e.g. "contains", "getFullYear", "now"."""
    display_name: builtins.str
    """Short label for a UI control, e.g. "Contains", "Year"."""
    description: builtins.str
    """Optional longer explanation of what the function does."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "display_name", b"display_name", "name", b"name"]) -> None: ...

global___FilterFunction = FilterFunction
