[workspace]
members = ["cargo:crates/sift_cli"]

[dist]
cargo-dist-version = "0.29.0"
tag-namespace = "rust/sift_cli/v"
ci = "github"
installers = ["shell"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",

  # Unfortunately we need openssl: https://github.com/axodotdev/cargo-dist/issues/786 
  # "aarch64-unknown-linux-gnu",
]
install-path = "CARGO_HOME"
install-updater = false
