name: Go Module Publish

on:
  workflow_dispatch:

jobs:
  go-ci:
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/go_ci.yaml

  publish-to-pkg-go-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#go/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish Go module
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/sift-stack/sift/go@$VERSION
