name: PyPI Publish

on:
  workflow_dispatch:

jobs:
  publish-to-testpypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    environment:
      name: pypi_dry_run
      url: https://test.pypi.org/p/sift_py
    permissions:
      id-token: write  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Pip install
        run: |
          python -m pip install --upgrade pip
          pip install '.[build]'
          pip install .

      - name: Build distributions
        working-directory: python
        run: |
          python -m build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./python/dist/
          repository-url: https://test.pypi.org/legacy/
