name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Version Bump and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
      - name: Create a GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Archive protos
        id: archive_protos
        run: tar -czvf sift_protos.tar.gz protos
      - name: Upload protos to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          file: sift_protos.tar.gz
          asset_name: sift_protos.tar.gz
         
