name: Crates Publish (Dry Run)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust-ci:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/rust_ci.yaml

  publish-to-crates-io-dry-run-sift_rs:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for sift_rs
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crate (dry run)
        run: cargo publish --dry-run
        working-directory: './rust/crates/sift_rs'

  publish-to-crates-io-dry-run-sift_error:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for sift_error
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crate (dry run)
        run: cargo publish --dry-run
        working-directory: './rust/crates/sift_error'

  publish-to-crates-io-dry-run-sift_connect:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for sift_connect
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crate (dry run)
        run: cargo publish --dry-run
        working-directory: './rust/crates/sift_connect'

  publish-to-crates-io-dry-run-sift_stream:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for sift_stream
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crate (dry run)
        run: cargo publish --dry-run
        working-directory: './rust/crates/sift_stream'

