name: Crates Publish (Dry Run)

on:
  workflow_dispatch:

jobs:
  rust-ci:
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/rust_ci.yaml

  publish-to-crate-io-dry-run:
    name: Do a dry run publish to crates.io
    needs: rust-ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          path: './rust'
          dry-run: true
