name: Crates Publish (Dry Run)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust-ci:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/rust_ci.yaml
  
  publish-to-crates-io-dry-run:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for the sift rust libraries
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crates (dry run)
        run: cargo publish --workspace --exclude sift-stream-bindings --manifest-path ./rust/Cargo.toml --locked --dry-run
