name: Crates Publish (Dry Run)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish from"
        type: string
        required: true

jobs:
  rust-ci:
    uses: ./.github/workflows/rust_ci.yaml
    with:
      ref: ${{ github.event.inputs.tag }}
  
  publish-to-crates-io-dry-run:
    runs-on: ubuntu-latest
    name: Do a dry run publish to crates.io for the sift rust libraries
    needs: rust-ci
    environment:
      name: crates.io (dry run)
    steps:
      - name: Checkout the specified tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crates (dry run)
        run: cargo publish --workspace --exclude sift-stream-bindings --manifest-path ./rust/Cargo.toml --locked --dry-run
